version: '3.8'

services:
    homeassistant:
        container_name: homeassistant
        image: "lscr.io/linuxserver/homeassistant:2023.7.2"
        volumes:
            - ./config:/config
            - ./configuration.yaml:/config/configuration.yaml
            - ./secrets.yaml:/config/secrets.yaml
            - /etc/localtime:/etc/localtime:ro
            - ./media:/media
        restart: unless-stopped
        privileged: true
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
    # home assistant has to run on network mode host to connect to physical devices in 
    # the house. It is configured with traefik by a file provider. See readme for more info.
